[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ils_screening_tm"
version = "0.1.4"
authors = [
  { name="Lorris Toucouère", email="lorris.toucouere@insa-toulouse.fr" },
]
description = "An interactive screening tool for ionic liquid cation generation, structural filtering, and melting point (Tm) prediction."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Chemistry",
]
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "tensorflow",
    "mordredcommunity",
    "ipywidgets",
    "IPython",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ils_screening_tm*"]
